---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp4-exp01-web
data:
  MYDATA_SOURCE_DIR: "static"
  MYTEMPLATE_SOURCE_DIR: "templates"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp4-exp01-initcont
data:
  S3BUCKET: "false"
  S3BUCKETNAME: "scw-initcont-exp01"
  S3FOLDER: "exp01-annoydata"

